/**
 * Schedules a large campaign in one shot to demonstrate behaviour under load.
 *
 *   npm run loadtest -- --count 1000 --hourly-limit 50 --delay 0
 *
 * With 1000 recipients all due immediately and an hourly limit well below that,
 * you should observe:
 *   - the enqueue itself finishing in seconds (chunked addBulk)
 *   - sends metered out by the worker limiter, never faster than
 *     MIN_SEND_INTERVAL_MS apart
 *   - once each sender's hourly quota is spent, the remainder being pushed into
 *     the next hour window in their original order — none marked failed
 */
import { parseArgs } from 'node:util';
import { prisma } from '../lib/prisma.js';
import { logger } from '../lib/logger.js';
import { env } from '../config/env.js';
import { scheduleCampaign } from '../queue/scheduler.js';
import { closeQueue } from '../queue/emailQueue.js';

const { values } = parseArgs({
  options: {
    count: { type: 'string', default: '1000' },
    'hourly-limit': { type: 'string' },
    delay: { type: 'string', default: '0' },
    subject: { type: 'string', default: 'Load test from the email scheduler' },
  },
  strict: false,
});

async function main(): Promise<void> {
  const count = Number(values.count);
  const delaySeconds = Number(values.delay);
  const hourlyLimit = values['hourly-limit']
    ? Number(values['hourly-limit'])
    : env.MAX_EMAILS_PER_HOUR_PER_SENDER;

  const user = await prisma.user.upsert({
    where: { googleSub: 'dev-local-user' },
    update: {},
    create: { googleSub: 'dev-local-user', email: 'dev@localhost', name: 'Local Dev User' },
  });

  // Ethereal accepts anything — these never leave the test server.
  const recipients = Array.from({ length: count }, (_, i) => `loadtest+${i + 1}@example.com`);

  const startedAt = Date.now();
  const result = await scheduleCampaign({
    userId: user.id,
    subject: String(values.subject),
    body: 'This message was generated by the load test script.',
    recipients,
    startAt: new Date(),
    delayMs: delaySeconds * 1000,
    hourlyLimit,
  });
  const elapsed = Date.now() - startedAt;

  console.log('\n──────────────────────────────────────────────');
  console.log(`  Scheduled ${result.totalScheduled} emails in ${elapsed}ms`);
  console.log(`  Campaign:            ${result.campaignId}`);
  console.log(`  Senders in rotation: ${result.senderCount}`);
  console.log(`  Hourly cap/sender:   ${hourlyLimit}`);
  console.log(`  Sustainable rate:    ${result.senderCount * hourlyLimit}/hour`);
  console.log(`  Send spacing:        >= ${env.MIN_SEND_INTERVAL_MS}ms between emails`);
  console.log('──────────────────────────────────────────────');
  console.log('  Watch the worker log, or poll GET /api/stats.\n');
}

main()
  .catch((err) => {
    logger.error({ err }, 'Load test failed');
    process.exitCode = 1;
  })
  .finally(async () => {
    await closeQueue();
    await prisma.$disconnect();
    process.exit(process.exitCode ?? 0);
  });
